services:
  # база данных
  db:
    image: postgres:15
    container_name: poe_postgres
    restart: always
    # Мы берем данные для логина из файла .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: poe_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_NAME} # Логин для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}  # Пароль для входа в pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
  # Наш Python-скрипт (сборщик)
  collector:
    build: ./collector  # Docker будет искать Dockerfile в папке collector
    container_name: poe_collector
    depends_on:
      - db             # Сначала запустится база, потом скрипт
    env_file:
      - .env           # Скрипт тоже будет видеть пароли из .env
    restart: always
