version: '3.8'

services:
  # Наша база данных
  db:
    image: postgres:15
    container_name: poe_postgres
    restart: always
    # Мы берем данные для логина из файла .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Наш Python-скрипт (сборщик)
  collector:
    build: ./collector  # Docker будет искать Dockerfile в папке collector
    container_name: poe_collector
    depends_on:
      - db             # Сначала запустится база, потом скрипт
    env_file:
      - .env           # Скрипт тоже будет видеть пароли из .env
    restart: always
